spring:
  application:
    name: 1v1-mcq-game
  data:
    mongodb:
      uri: mongodb://localhost:27017/db
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration